### ISSUE TITLE
Could not load imported ontology

### ISSUE THREAD

**Issue by matentzn** [OpenLHS/LABO#1]
As part of our OBO wide effort to establish common quality control, we noticed that labo does not parse currently:

```
org.semanticweb.owlapi.model.UnloadableImportException: Could not load imported ontology: 

<http://purl.obolibrary.org/obo/iao/iao-edit.owl> Cause: http://purl.oclc.org/obo/iao/iao-edit.owl

```

The issue here is not only that the import does not resolve; you also should not (ideally ever) import the edit file of an ontology (iao-edit.owl). Better to use the proper OBO purl (http://purl.obolibrary.org/obo/iao.owl)!

**Comment by nlharris** [comment]
See also https://github.com/OBOFoundry/OBOFoundry.github.io/issues/1444

**Comment by pfabry** [comment]
Hi, it seems I missed your issue. Sorry about that. 
I will look into it and get back to you as soon as possible.

**Comment by pfabry** [comment]
Imports sources have been updated + merged version available in root directory.

**Comment by matentzn** [comment]
This is great, fixed! Loads now in dashboard:

http://dashboard.obofoundry.org/dashboard/index.html
